### ISSUE TITLE
Tailwind: `purge > whitelist` is now `safelist`

### ISSUE THREAD

**Issue by adamkiss** [philipmarnef/k3-scaffold#11]
## `whitelist` option dropped
The Tailwind config option for safelisting classes from being purged is now (and in v3 going forwards) not in the `purge.options.whitelist` key: https://github.com/philipmarnef/k3-scaffold/blob/8336db7853085f7f0a9dba39c700ef094ba44064/tailwind.config.js#L3-L12

## v2

See: https://tailwindcss.com/docs/optimizing-for-production#safelisting-specific-classes

```js
// tailwind.config.js
{
  purge: {
    content: [/* files */],
    safelist: [/* safelist */], // Tailwind safelist
    options: {
      safelist: [/* safelist */] // safelist as an option sent to purgecsss
    }
  }
}
```

## v3

Going forward, PurgeCSS is going to be dropped altogether, with purging/safelisting handled by TailwindCSS itself: https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0-alpha.1 and available via config root keys `content` and `safelist`>

```js
// tailwind.config.js
module.exports = {
  content: {
    files: ['./src/**/*.html' /* ... */],
  },
  safelist: [
    'font-bold',
    'text-center',
    { pattern: /bg-(red|blue|green)/, variants: ['hover', 'focus'] },
  ],
  // ...
}
```

**Comment by philipmarnef** [comment]
Ha, missed that one. Cheers.

**Comment by philipmarnef** [comment]
This was fixed ages ago :-)
